apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e2e-basic-1777534156314
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/test-image:github-d3f404301c86a3d0b273eb635185a5f37cbe1309
          name: container-image
